name: CI/CD

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
    
jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    outputs:
      src: ${{ steps.filter.outputs.src }}
      test: ${{ steps.filter.outputs.test }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
              - 'Cargo.toml'
            test:
              - '.github/workflows/ci-cd.yml'
              - 'integration_tests/**'
              - 'run_tests.sh'
  ci-cd:
    needs: changes
    runs-on: ubuntu-latest

    container: gabriel0simpleg/cp-microservice:main
    services:
      rabbitmq:
        image: rabbitmq:3.12
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          
    timeout-minutes: 10

    if: ${{ needs.changes.outputs.src == 'true' || needs.changes.outputs.test == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python integration tests dependencies
        run: |
          python3 -m venv ./venv
          source ./venv/bin/activate
          pip install amqp_api_client_py aio_pika
      - name: Run integration tests
        run: |
          source ./venv/bin/activate
          chmod +x run_tests.sh
          ./run_tests.sh
        env:
          AMQP_API_CONNECTION_URI: "amqp://guest:guest@127.0.0.1:5672"
      - name: Publish on crates.io
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish --allow-dirty
