name: CI/CD

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
    
jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            src:
              - 'src/**'
              - 'Cargo.toml'
            test:
              - 'integration_tests/**'
              - 'run_tests.sh'
  ci-cd:
    needs: changes
    runs-on: ubuntu-latest
    timeout-minutes: 10

    if: ${{ needs.changes.outputs.src == 'true' || needs.changes.outputs.test == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Replace placeholder version
        run: |
          sed -i 's/5123.0.0/${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.${{ env.PATCH_VERSION }}/' Cargo.toml
          echo "Version: ${{ vars.MAJOR_VERSION }}.${{ vars.MINOR_VERSION }}.$PATCH_VERSION"
        env:
          PATCH_VERSION: ${{ github.run_number }}
        
      - name: Build
        run: cargo build --release --verbose
      - name: Run unit tests
        run: cargo test --verbose
      - name: Start RabbitMQ
        run: |
          docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3.12-management &
          sleep 6
      - name: Install Python integration tests dependencies
        run: |
          pip3 install amqp_api_client_py aio_pika
      - name: Run integration tests
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh
        env:
          AMQP_API_CONNECTION_URI: "amqp://guest:guest@127.0.0.1:5672"
      - name: Publish on crates.io
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish --allow-dirty
