name: CI

on:
  push:

env:
  CARGO_TERM_COLOR: always
    
jobs:
  ci:

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Replace placeholder version
        run: |
          sed -i 's/5123.0.0/$MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION'
          echo "Version: $MAJOR_VERSION.$MINOR_VERSION.$PATCH_VERSION"
        env:
          PATCH_VERSION: ${{ github.run_attempt }}
        
      - name: Build
        run: cargo build --release --verbose
      - name: Run unit tests
        run: cargo test --verbose
      - name: Run integration tests
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh
    
