name: python

on:
  push:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
    
jobs:
  ci-cd:
    runs-on: ubuntu-latest

    container: rust:1.72.0
    services:
      rabbitmq:
        image: rabbitmq:3.12
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          
    timeout-minutes: 10
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Python integration tests dependencies
        run: |
          apt-get update
          apt-get -y install python3 python3-pip python3-venv
          python3 -m venv ./venv
          chmod +x ./venv/bin/activate
          ./venv/bin/activate
          pip3 install amqp_api_client_py aio_pika
      - name: Run integration tests
        run: |
          chmod +x run_tests.sh
          ./run_tests.sh
        env:
          AMQP_API_CONNECTION_URI: "amqp://guest:guest@127.0.0.1:5672"
      - name: Publish on crates.io
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo publish --allow-dirty
